workflows:
  ios-debug:
    name: FundiHub iOS Debug
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          rm -f Podfile
          flutter pub get
          pod install --repo-update
          cd ..

      - name: Build iOS no codesign
        script: |
          rm -rf ~/Library/Caches/org.swift.swiftpm
          rm -rf ~/Library/Developer/Xcode/DerivedData
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app